dist: trusty
sudo: false
language: rust
rust: nightly

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_TEST_THREADS=1
    - CARGO_BUILD_JOBS=1
    - MAKE_PARALLELISM=1

cache:
  - cargo

script:
  - travis_wait sleep 1000000000 &
  - cargo test --verbose
