#fn_args_layout="block"
#array_layout="block"
#where_style="rfc"
#generics_indent="block"
#fn_call_style="block"
#fn_args_density="compressed"
#where_density="compressed"
#fn_call_width=80
array_width=80
# chain_one_line_max=80
use_try_shorthand=true
error_on_line_overflow=false
